In [2]:
import numpy as np

In [9]:
a1 = np.array([1,2,3,4,5,8])
a2 = np.array([6,7,8,9,10,11])

a2

array([ 6,  7,  8,  9, 10, 11])

In [10]:
arr1 =a1 + a2

array([ 7,  9, 11, 13, 15, 19])

In [11]:
arr2 = a1-a2
arr2

array([-5, -5, -5, -5, -5, -3])

In [12]:
arr3 = a1*a2
arr3

array([ 6, 14, 24, 36, 50, 88])

In [15]:
arr4 = a2/a1
arr4

array([6.        , 3.5       , 2.66666667, 2.25      , 2.        ,
       1.375     ])

In [16]:
a1//a2

array([0, 0, 0, 0, 0, 0])

In [17]:
a2//a1

array([6, 3, 2, 2, 2, 1])

In [19]:
l =[20,30,40,50,60,70,80,90]
arr = np.array(l)
arr

array([20, 30, 40, 50, 60, 70, 80, 90])

In [20]:
arr+10

array([ 30,  40,  50,  60,  70,  80,  90, 100])

In [22]:
arr2 = np.arange(1,26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [23]:
arr3 = np.arange(26,51).reshape(5,5)
arr3

array([[26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [24]:
arra = arr2 + arr3
arra

array([[27, 29, 31, 33, 35],
       [37, 39, 41, 43, 45],
       [47, 49, 51, 53, 55],
       [57, 59, 61, 63, 65],
       [67, 69, 71, 73, 75]])

In [28]:
arra-1

array([[26, 28, 30, 32, 34],
       [36, 38, 40, 42, 44],
       [46, 48, 50, 52, 54],
       [56, 58, 60, 62, 64],
       [66, 68, 70, 72, 74]])

In [29]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [30]:
slice = a[:6]
slice = slice*10
slice

array([10, 20, 30, 40, 50, 60])

In [31]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [40]:
b = np.arange(1,26).reshape(5,5)
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [43]:
c = b
c*10

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100],
       [110, 120, 130, 140, 150],
       [160, 170, 180, 190, 200],
       [210, 220, 230, 240, 250]])

In [45]:
b 


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [49]:
A =np.array([[1,2,3],[4,5,6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [50]:
B =np.array([[6,7,8],[8,9,10]])
B

array([[ 6,  7,  8],
       [ 8,  9, 10]])

In [ ]:
###MATRIX MULTIPLICATION###
A @ B.T

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)