In [25]:
import numpy as np

In [26]:
##basic array creation## 

In [27]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [28]:
a = [1,2,3.5,]
a

[1, 2, 3.5]

In [29]:
np.array(a)

array([1. , 2. , 3.5])

In [30]:
l =[[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [31]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [33]:
arr = np.zeros(7)
arr

array([0., 0., 0., 0., 0., 0., 0.])

In [34]:
arr = np.zeros((4,10))
arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [40]:
arr = np.linspace(0,1,3)
arr

array([0. , 0.5, 1. ])

In [41]:
arr = np.random.randn(50)
arr

array([ 0.60958161, -1.50714997,  0.91879182, -0.23260754, -0.94745668,
       -0.44419415, -0.08957029, -0.10340934, -0.81533021, -1.83691897,
        0.1376302 , -1.31143686, -0.56974892, -2.40187556, -0.84319207,
       -0.81615618,  1.65883832,  0.28963699, -0.36307094, -0.52687158,
       -1.46530778,  0.44041389, -0.43978107,  0.43455291, -0.97092447,
        0.75375254,  0.72460754,  0.09424548,  0.06446776, -0.3401383 ,
        0.30962776, -1.05511745,  0.71996883, -0.04655639,  0.04425068,
       -1.09946153, -0.45711641,  0.52365832,  0.42512097,  0.73407928,
        0.08620951, -1.18419057,  0.54119582,  2.03373071,  0.4710208 ,
        0.47022756, -0.23210426, -1.2250984 ,  0.68059628,  0.13296292])

In [47]:
ar = np.random.randint(20,50,20)
ar

array([46, 43, 47, 33, 32, 21, 43, 43, 32, 29, 45, 45, 25, 30, 27, 28, 27,
       44, 21, 39], dtype=int32)

In [52]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [53]:
arr.shape

(3, 3)

In [54]:
arr.size

9

In [55]:
arr.dtype

dtype('int64')

In [56]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [57]:
arr.min()

np.int64(1)

In [58]:
arr.max()

np.int64(9)

In [59]:
arr.sum()

np.int64(45)

In [60]:
np.sum(arr,axis = 0)

array([12, 15, 18])

In [61]:
np.sum(arr,axis=1)

array([ 6, 15, 24])

In [62]:
arr.mean()

np.float64(5.0)

In [63]:
arr.std()

np.float64(2.581988897471611)

In [64]:
arr.argmax()

np.int64(8)

In [65]:
arr.argmin()

np.int64(0)

In [67]:
arr = np.arange(1,51)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [69]:
arr =arr.reshape(5,10)
arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [70]:
arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])